#!/usr/bin/env bash
# Installs and configures Nginx to listen on port 8080

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo sed -i 's/#user nginx;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx service
sudo service nginx restart
