#!/usr/bin/env bash
sudo apt update
sudo apt install -y nginx
sudo sed -i 's/listen 80$/listen 8080/' /etc/nginx/sites-available/default
sudo sed -i 's/#user nginx;/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx restart
